### ISSUE TITLE
Blocking Google fonts causes display issue.

### ISSUE THREAD

**Issue by markx2** [MKNUG/mknug.org#1]
I block googleapis.com and when I visit the site I see this: 

<img width="826" alt="screen shot 2015-07-08 at 11 11 38" src="https://cloud.githubusercontent.com/assets/7057656/8568107/be1c426a-2562-11e5-9616-9decd577e624.png">

**Comment by TinyExplosions** [comment]
Have moved all the icon font stuff locally, so this shouldn't be an issue any more.
